apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-api
spec:
  selector:
    matchLabels:
      app: store-api
  template:
    metadata:
      labels:
        app: store-api
    spec:
      containers:
      - name: store-api
        image: amrmousa1682/store-api:latest
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
